services:
  - type: web
    name: lstm-stock-api
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /health
    envVars:
      - key: LOG_LEVEL
        value: INFO

  - type: web
    name: lstm-stock-dashboard
    runtime: docker
    region: oregon
    plan: free
    dockerfilePath: ./Dockerfile.dashboard
    dockerContext: .
    healthCheckPath: /_stcore/health
    envVars:
      - key: API_URL
        value: https://pos-tech-mlet-fase-4.onrender.com
